#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#Install installService.sh from install_dir/bin
if [[ -f ${INSTALL_DIR}/bin/installService.sh ]]; then
    set +u
    # we do not want this to register service as we provide our own upstart
    sed -i 's/installService$//g' ${INSTALL_DIR}/bin/installService.sh
    sed -i 's/prepareTomcat$//g' ${INSTALL_DIR}/bin/installService.sh
    
    . ${INSTALL_DIR}/bin/installService.sh
    set -u
else
    fail "Make sure the installation is correct. Can not find ${INSTALL_DIR}/bin/installService.sh"
    exit 21
fi

