#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

debug "start/run: Starting agent using '${INSTALL_DIR}/bamboo-agent-installer.jar'"
CUSTOM_AGENT_FLAGS="${CUSTOM_AGENT_FLAGS:-}"
START_AGENT_CMD=$( run_cmd su - "${INSTANCE_USER}" -c \"java -Dbamboo.home=\\\"${HOME_DIR}\\\" -Ddisable_agent_auto_capability_detection=true -jar \\\"${INSTALL_DIR}/bamboo-agent-installer.jar\\\" ${CUSTOM_AGENT_FLAGS}" console\" )
debug "${START_AGENT_CMD}"
if [[ "$(get_std_return ${START_AGENT_CMD})" != "0" ]]; then
    fatal "start/run: Error while starting Bamboo Agent: $(get_std_out ${START_AGENT_CMD})"
    return 46
fi

