#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

for _dir in "${INSTALL_DIR}" "${HOME_DIR}" ; do
    if [[ ! -d "${_dir}" ]]; then
        debug "common/install/create_dirs: install: create_dirs: Created \"${_dir}\""
        mkdir -p "${_dir}"
        chown "${INSTANCE_USER}":"${INSTANCE_GROUP}" "${_dir}"
        chmod 0755 "${_dir}"
    else
        fatal "common/install/create_dirs: install: During install \"${_dir}\" already exists... terminating"
        exit 10
    fi
done

