#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

TARBALL="$PARAMS"

if [[ -z "${TARBALL}" || ! -f "${TARBALL}" ]]; then
    fatal "install/expand_tarball: tarball \"${TARBALL}\" does not exist"
    exit 20
fi

debug "install/expand_tarball: atlassian: install: expand_tarball: Expanding '${TARBALL}' into '${INSTANCE_DIR}/install'"
EXTRACT_TARBALL_RESULT=$( run_cmd tar -zxf "${TARBALL}" \
    --group="${INSTANCE_GROUP}" \
    --owner="${INSTANCE_USER}" \
    -C "${INSTANCE_DIR}/install" \
    --strip-components=1 )
debug "${EXTRACT_TARBALL_RESULT}"
if [[ "$(get_std_return ${EXTRACT_TARBALL_RESULT})" != "0" ]]; then
    fatal "install/expand_tarball: Error while expanding tarball: $(get_std_out ${EXTRACT_TARBALL_RESULT})"
    return 32
fi

run_cmd chown -R "${INSTANCE_USER}":"${INSTANCE_GROUP}" "${INSTANCE_DIR}/install"
