#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [[ -z "${PROVIDER_FILESYSTEM_DIR:-}" ]]; then
    fatal "Configuration PROVIDER_FILESYSTEM_DIR does not exist. Provide it please."
    exit 21
fi

mkdir -p "${PROVIDER_FILESYSTEM_DIR}"
chown -R "${INSTANCE_USER}":"${INSTANCE_GROUP}" "${PROVIDER_FILESYSTEM_DIR}"

