#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

 # adjust db config file  install_dir/etc/storage.properties to contain e.g.:
if [[ -z "${DB_TYPE:-}" ||
    -z "${DB_DRIVER:-}" ||
    -z "${DB_URL:-}" ||
    -z "${DB_USER:-}" ||
    -z "${DB_PASS:-}" ||
    -z "${PROVIDER_FILESYSTEM_DIR:-}" ]]; then
    fatal 'You have to provide database connection properties: DB_TYPE, DB_DRIVER, DB_USER, DB_PASS and DB_URL'
    exit 21
fi

#Prepare Artifactory to use mysql do the same tasks as are in ${INSTALL_DIR}/bin/configure.mysql.sh 
# that does this interactivelly
DB_CONFIG_FILE="${INSTALL_DIR}/etc/storage.properties"
debug "Overwriting ${DB_CONFIG_FILE} with mysql settings"
    cat <<DB_FILE > "${DB_CONFIG_FILE}"
type=${DB_TYPE}
driver=${DB_DRIVER}
url=${DB_URL}
username=${DB_USER}
password=${DB_PASS}

## Determines where the actual artifacts binaries are stored. Available options:
## filesystem - binaries are stored in the filesystem (recommended, default)
## fullDb     - binaries are stored as blobs in the db, filesystem is used for caching
## cachedFS   - binaries are stored in the filesystem, but a front cache (with faster access) is added
## IMPORTANT NOTE: This property should not be change after the initial setup. To change binaries storage you have to export and import
#binary.provider.type=filesystem
## Determines the maximum filesystem cache size in bytes when using binary provider type fullDb or cachedFS. Default is 5GB
## Supported units are GB (gigabytes), MB (megabytes) and KB (kilobytes)
#binary.provider.cache.maxSize=5GB

binary.provider.type=filesystem
binary.provider.filesystem.dir=${PROVIDER_FILESYSTEM_DIR}
DB_FILE

chown "${INSTANCE_USER}":"${INSTANCE_GROUP}" "${DB_CONFIG_FILE}"

