#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is a replacement for setenv.sh that is called in catalina.sh
# as we are running java directly instead of starting the process via catalina.sh 
# we need to set all parameters as they are set in setenv.sh
. /etc/opt/jfrog/artifactory/default
debug "Max number of open files: `ulimit -n`"
debug "Using ARTIFACTORY_HOME: ${ARTIFACTORY_HOME}"
debug "Using ARTIFACTORY_PID: ${ARTIFACTORY_PID}"
# CATALINA_OPTS is set here not in default
export CATALINA_OPTS="${JAVA_OPTIONS} -Dartifactory.home=${ARTIFACTORY_HOME}"
#Exported in /etc/opt/jfrog/artifactory/default as $ARTIFACTORY_HOME/run/artifactory.pid
export CATALINA_PID="${ARTIFACTORY_PID}"
export CATALINA_HOME="${TOMCAT_HOME}"

