#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SYSTEMD_HOME="${SYSTEMD_HOME:-/etc/systemd/system/}"

# Reload Upstart configuration, since symlinks are not auto-read by default
if [ -L /sbin/init ] &&  [[ $(readlink /sbin/init) == *"systemd"* ]]; then
    # MANUAL_UPSTART renamed to MANUAL_SERVICE, left both for backwards compatibility
    if [[ "${MANUAL_UPSTART:-}" == "1" || "${MANUAL_SERVICE:-}" == "1" ]]; then
        if [[ "${MANUAL_UPSTART:-}" == "1" ]]; then
            warn "Using MANUAL_UPSTART is deprecated, please use MANUAL_SERVICE instead."
        fi
        RELOAD_CONFIG_RESULT=$( run_cmd systemctl disable ${INSTANCE_NAME} )
        if [[ "${START_ELASTICSEARCH:-}" != '' ]]; then
            ENABLE_SEARCH_RESULT=$( run_cmd systemctl disable ${SEARCH_SERVICE_NAME} )  
        fi
    else
        if [[ "${START_ELASTICSEARCH:-}" != '' ]]; then
            ENABLE_SEARCH_RESULT=$( run_cmd systemctl enable ${SEARCH_SERVICE_NAME} )  
        fi
        RELOAD_CONFIG_RESULT=$( run_cmd systemctl enable ${INSTANCE_NAME} )
    fi
else
    RELOAD_CONFIG_RESULT=$( run_cmd initctl reload-configuration )
fi

debug "${RELOAD_CONFIG_RESULT}"
if [[ "$(get_std_return ${RELOAD_CONFIG_RESULT})" != "0" ]]; then
    fatal "install_service: Error while reloading configuration"
    return 32
fi 
