#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
  
VERSIONS_COMPARED_RESULT=$( run_cmd "version_comparison '7.2.99' '<' '${VERSION}'" )
if [[ "$(get_std_return ${VERSIONS_COMPARED_RESULT})" == "0" ]]; then
  JIRA_XML_FILE="${HOME_DIR}/dbconfig.xml"
  if [[ -r "${JIRA_XML_FILE:-}" ]]; then
    
sed -i 's/=storage_engine=/=default_storage_engine=/' "${JIRA_XML_FILE}" 

  # if the DB is mysql add validation-query-timeout, if not do not
  if [[ "${DB_TYPE}" == "mysql" ]]; then
    debug "jira/upgrade/fix_db_setup: MySQL detected, setting validation-query-timeout"
    VAL_QUERY_TIMEOUT_SET="set \$datasources/validation-query-timeout/#text \"${DB_VALIDATION_QUERY_TIMEOUT:-3}\"" 
  else
    debug "jira/upgrade/fix_db_setup: Non MySQL detected, skipping validation-query-timeout"
    VAL_QUERY_TIMEOUT_SET=""
  fi

    augtool -LA -e <<EOF
set /augeas/load/xml/lens "Xml.lns"
set /augeas/load/xml/incl "${JIRA_XML_FILE}"
load
defvar dbconfig_xml "/files/${JIRA_XML_FILE}"
defvar database_config \$dbconfig_xml/jira-database-config
defvar datasources \$database_config/jdbc-datasource
set \$database_config/name/#text "${DB_DATASOURCE_NAME:-defaultDS}"
set \$database_config/delegator-name/#text "${DB_DELEGATOR_NAME:-default}"
set \$datasources/pool-min-size/#text "${DB_MIN_POOL_SIZE:-20}"
set \$datasources/pool-max-size/#text "${DB_MAX_POOL_SIZE:-20}"
set \$datasources/pool-max-wait/#text "${DB_POOL_MAX_WAIT:-30000}"
set \$datasources/pool-max-idle/#text "${DB_POOL_MAX_IDLE:-20}"
set \$datasources/pool-remove-abandoned/#text "${DB_POOL_REMOVE_ABANDONED:-true}"
set \$datasources/pool-remove-abandoned-timeout/#text "${DB_POOL_REMOVE_ABANDONED_TIMEOUT:-300}"
set \$datasources/pool-test-on-borrow/#text "${DB_POOL_TEST_ON_BORROW:-false}"
set \$datasources/validation-query/#text "${DB_VALIDATION_QUERY:-select 1}"
set \$datasources/min-evictable-idle-time-millis/#text "${DB_MIN_EVIDENCE_IDLE_TIME_MILLIS:-60000}"
set \$datasources/time-between-eviction-runs-millis/#text "${DB_TIME_BETWEEN_EVICTION_RUNS_MILLIS:-300000}"
set \$datasources/pool-test-while-idle/#text "${DB_POOL_TEST_WHILE_IDLE:-true}"
${VAL_QUERY_TIMEOUT_SET}
save
print /augeas//error
EOF

  fi
fi

