#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [[ "$(uname)" != "Linux" ]]; then
    fatal "sonarqube/stop/stop: Error: unsupported Operating system $(uname)"
    return 99
else
    if [[ "$(uname -i)" == "x86_64" ]]; then
        WRAPPER_DIR="${INSTANCE_DIR}/install/bin/linux-x86-64"
    else
        WRAPPER_DIR="${INSTANCE_DIR}/install/bin/linux-x86-32"
    fi
fi

RUN_CMD="su \"${INSTANCE_USER}\" bash -c \"${WRAPPER_DIR}/sonar.sh stop\""

debug "sonarqube/stop/stop: Running: ${RUN_CMD}"

SONARQUBE_STOP_CMD=$( run_cmd "${RUN_CMD}" )
debug "${SONARQUBE_STOP_CMD}"

if [[ "$(get_std_return ${SONARQUBE_STOP_CMD})" != "0" ]]; then   
  signal_stop_process "sonarqube/stop/stop"
fi
