#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Atlassian specific versioning of files, in case VERSION variable is not provided.
# Determine required version. if VERSION can not be found try to get it from TARBALL filename

OLD_VERSION=$( head -1 "${INSTANCE_DIR}/.version" )
debug "bitbucket/update/elasticsearch_upgrade: Looking at ES upgrade, only needed if old was < 5.7.0 and new is >= 5.7.0"

# if the old version was
OLD_VERSIONS_COMPARED_RESULT=$( run_cmd "version_comparison '5.6.99' '<' '${OLD_VERSION}'" )
NEW_VERSIONS_COMPARED_RESULT=$( run_cmd "version_comparison '5.6.99' '<' '${VERSION}'" )
if [[ "$(get_std_return ${OLD_VERSIONS_COMPARED_RESULT})" == "0" ]]; then
	debug "bitbucket/update/elasticsearch_upgrade: Old version of ES is already >= 5.7.0, no action needed"
else
    if [[ "$(get_std_return ${NEW_VERSIONS_COMPARED_RESULT})" == "0" ]]; then
    	if [[ -f "${HOME_DIR}/shared/search/elasticsearch.yml" ]]; then
            debug "bitbucket/update/elasticsearch_upgrade: attempting to remove ${HOME_DIR}/shared/search/elasticsearch.yml"
            rm -f "${HOME_DIR}/shared/search/elasticsearch.yml"
        else
        	debug "bitbucket/update/elasticsearch_upgrade: attempting to remove ${HOME_DIR}/shared/search/elasticsearch.yml"
    	fi
    else
    	debug "bitbucket/update/elasticsearch_upgrade: New version of ES is < 5.7.0, no action needed"
    fi
fi
