#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Atlassian specific versioning of files, in case VERSION variable is not provided.
# Determine required version. if VERSION can not be found try to get it from TARBALL filename

if [ -L /sbin/init ] &&  [[ $(readlink /sbin/init) == *"systemd"* ]]; then
    SERVICE_STATUS_SEARCH_STRING="Active: active"
else
    SERVICE_STATUS_SEARCH_STRING="running"
fi

# if the old version was
VERSIONS_COMPARED_RESULT=$( run_cmd "version_comparison '4.5.2' '<' '${OLD_VERSION}'" )
if [[ "$(get_std_return ${VERSIONS_COMPARED_RESULT})" == "0" ]]; then
	debug "bitbucket/update/elasticsearch_upgrade: Attempting to stop ES service"
	RESULT_SERVICE_RUNNING=$( run_cmd "service '${SEARCH_SERVICE_NAME}' status | grep '${SERVICE_STATUS_SEARCH_STRING}'" )
    debug "${RESULT_SERVICE_RUNNING}"
    if [[ $( get_std_return ${RESULT_SERVICE_RUNNING} ) == "0" ]]; then
        run_cmd "service ${SEARCH_SERVICE_NAME} stop"
    fi
else
	debug "bitbucket/update/stop_es_service: Old Version does not have ES, no action needed"
fi
