#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# check if required version should contain elasticsearch
VERSIONS_COMPARED_RESULT=$( run_cmd "version_comparison '4.5.2' '<' '${VERSION}'" )
if [[ "$(get_std_return ${VERSIONS_COMPARED_RESULT})" == "0" ]]; then
    RESULT_INSTALL_SERVICE_AVST_APP_CMD=$(run_cmd avst-app "${DEBUG_OPTION:-}" "${INSTANCE_NAME}" install-service)
    debug "${RESULT_INSTALL_SERVICE_AVST_APP_CMD}"
    if [[ "$(get_std_return ${RESULT_INSTALL_SERVICE_AVST_APP_CMD})" != "0" ]]; then
        fatal "common/upgrade/check_install_search_service: Failed while installing search service, check logs for more info: $(get_std_out ${RESULT_INSTALL_SERVICE_AVST_APP_CMD})"
        return 39
    fi    
fi

