#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Create directories that Tomcat requires
for _dir in 'logs' 'temp' 'work' 'webapps'; do
    _dir="${TOMCAT_DIR}/${_dir}"
    if [ ! -d "$_dir" ]; then
        warn "tomcat/modify/tomcat_create_dirs: Creating \"$_dir\""
        mkdir -v -p "$_dir"
    fi
done

# Make sure permissions are set correctly 
chown -R "${INSTANCE_USER}":"${INSTANCE_GROUP}" "${TOMCAT_DIR}/logs"
chown -R "${INSTANCE_USER}":"${INSTANCE_GROUP}" "${TOMCAT_DIR}/temp"
chown -R "${INSTANCE_USER}":"${INSTANCE_GROUP}" "${TOMCAT_DIR}/work"
chown -R root:root "${TOMCAT_DIR}/webapps"

