#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

JVM_MINIMUM_MEMORY="${JVM_MINIMUM_MEMORY:-512m}"
JVM_MAXIMUM_MEMORY="${JVM_MAXIMUM_MEMORY:-2g}"
JVM_MAX_PERM_SIZE="${JVM_MAX_PERM_SIZE:-256m}"

JAVA_GC1_OPTIONS="${JAVA_GC1_OPTIONS:--server -XX:+UseG1GC}"
JAVA_CUSTOM_D_OPTIONS="${JAVA_CUSTOM_D_OPTIONS:--Dartifactory.home=${INSTALL_DIR}}"
JAVA_PERFORMANCE_OPTIONS="${JAVA_PERFORMANCE_OPTIONS:--XX:PermSize=128m -Xss256k}"
JAVA_ENDORSED_DIRS="${JAVA_ENDORSED_DIRS:-${TOMCAT_DIR}/endorsed}"

log_set_variable JVM_MAXIMUM_MEMORY
log_set_variable JVM_MINIMUM_MEMORY
log_set_variable JVM_MAX_PERM_SIZE

