#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

for _dir in 'work' 'temp' ; do
    if [ -d "${TOMCAT_DIR}/${_dir}" ]; then
        debug "tomcat/modify/tomcat_clean_dirs: Clearing ${TOMCAT_DIR}/${_dir}"
        find "${TOMCAT_DIR}/${_dir}" -mindepth 1 -maxdepth 1 -print0 | \
        su - "${INSTANCE_USER}" -c "xargs -0rP 10 rm -rf"
    fi
done

