#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

APP_SERVER="tomcat"
# Realtive to INSTALL_DIR, but this isn't set yet
TOMCAT_SUFFIX=""
WEBAPP_SUFFIX="confluence"

log_set_variable APP_SERVER
log_set_variable TOMCAT_SUFFIX
log_set_variable WEBAPP_SUFFIX

