#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# expecting to point to folder that contains BASE_DIR backup
if [[ ! -z "${BACKUP_SYSTEM_LOCATION:-}" && -d "${BACKUP_SYSTEM_LOCATION}/${BASE_DIR}/${INSTANCE_NAME}" ]]; then

    cp -rp "${BACKUP_SYSTEM_LOCATION}${BASE_DIR}/${INSTANCE_NAME}" "${BASE_DIR}/" && rm -fr "${BACKUP_SYSTEM_LOCATION}${BASE_DIR}/${INSTANCE_NAME}"
    
    # Fix ownership
    chown -R "${INSTANCE_USER}:${INSTANCE_GROUP}" "${INSTANCE_DIR}"
    debug "restore/restore_system: ${BASE_DIR}/${INSTANCE_NAME} directory restored from backup."
else
    fatal "restore/restore_system: BACKUP_SYSTEM_LOCATION not set or required folders not found, skipping system restore.\
    Make sure the BACKUP_SYSTEM_LOCATION contains ${BASE_DIR} directory."
    return 45
fi

