#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SHUTDOWN_PORT="${SHUTDOWN_PORT:-8020}"
CONTEXT_PATH="${CONTEXT_PATH:-}"
HTTP_PORT="${HTTP_PORT:-8081}"

TOMCAT_RESOURCE_COUNT=1
TOMCAT_RESOURCE_NAME='UserTransaction'
TOMCAT_RESOURCE_AUTH='Container'
TOMCAT_RESOUTCE_TYPE='javax.transaction.UserTransaction'
TOMCAT_RESOURCE_FACTORY='org.objectweb.jotm.UserTransactionFactory'
TOMCAT_RESOURCE_JOTM_TIMEOUT='60'

log_set_variable SHUTDOWN_PORT
log_set_variable CONTEXT_PATH
log_set_variable HTTP_PORT
log_set_variable TOMCAT_RESOURCE_COUNT
log_set_variable TOMCAT_RESOURCE_NAME
log_set_variable TOMCAT_RESOURCE_AUTH
log_set_variable TOMCAT_RESOUTCE_TYPE
log_set_variable TOMCAT_RESOURCE_FACTORY
log_set_variable TOMCAT_RESOURCE_JOTM_TIMEOUT

