#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [[ ${REMOVE_TOMCAT_ACCESS_LOGGING:-0} -eq "0" ]]; then
    REMOVE_TOMCAT_ACCESS_LOGGING_CMD="set \$service/Engine/Valve/#attribute/enabled true"
else
    REMOVE_TOMCAT_ACCESS_LOGGING_CMD="set \$service/Engine/Valve/#attribute/enabled false"
fi

augtool -LA ${AUGTOOL_DEBUG} <<EOF
set /augeas/load/xml/lens "Xml.lns"
set /augeas/load/xml/incl "${SERVER_XML_FILE}"
load
defvar server_xml "/files/${SERVER_XML_FILE}"
defvar service \$server_xml/Server/Service

${REMOVE_TOMCAT_ACCESS_LOGGING_CMD}
save
print /augeas//error

EOF
