#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# check that this is bitbucket version 5 or higher
if [[ ${PRODUCT} == "bitbucket" && ${MAJOR_VER:-0} -ge 5 ]]; then
    BITBUCKET_PROPERTIES_FILE="${HOME_DIR}/shared/bitbucket.properties"

    # ensure property file exists
    if [[ ! -r ${BITBUCKET_PROPERTIES_FILE} ]]; then
        debug "bitbucket/modify/set_session_timeout: Could not find bitbucket.properties, creating"
        mkdir -p ${HOME_DIR}/shared/
        touch ${BITBUCKET_PROPERTIES_FILE}
        chown -R ${INSTANCE_USER} ${HOME_DIR}/shared/
    fi

     # modify the BITBUCKET_PROPERTIES_FILE with the timeout settings
    AUGFILE="
set /augeas/load/properties/lens "Properties.lns"
set /augeas/load/properties/incl "${BITBUCKET_PROPERTIES_FILE}"
load
defvar prop /files${BITBUCKET_PROPERTIES_FILE}
set  \$prop/server.session.timeout \"${TOMCAT_SESSION_TIMEOUT:-30}\"
"
    augtool -LA -e <<EOF
${AUGFILE}
save
print /augeas//error
EOF
else
    debug "bitbucket/modify/set_session_timeout: skipping as bitbucket < 5 uses web.xml for session timeout"
fi