#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Sets java defaults for all atlasian products

if [[ -z "${HOME_DIR_PROPERTY:-}" && "${HOME_DIR:-}" != '' ]]; then
    eval $( echo "${HOME_DIR}" | egrep -q '[[:space:]]' )
    if [[ $? -ne 0 ]]; then
        warn ""
        warn "--------------------------------------------------------------------------------------------------------------------"
        warn "   WARNING : You cannot have a HOME_DIR environment variable set with spaces in it.  This variable is being ignored"
        warn "--------------------------------------------------------------------------------------------------------------------"
    else
        HOME_DIR_PROPERTY="${HOME_DIR_FLAG}=${HOME_DIR}"
    fi
else
    fatal "HOME_DIR not set. Please provide it somewhere..."
    exit 13
fi

DEF_JAVA_CUSTOM_D_OPTIONS="-Djava.awt.headless=true \
                        -Dfile.encoding=UTF-8"

DEF_JAVA_BEHAVIORAL_OPTIONS="-XX:+UseParallelGC \
                        -XX:+UseParallelOldGC \
                        -XX:+DisableExplicitGC"

DEF_JAVA_GC1_OPTIONS=""

DEF_JAVA_PERFORMANCE_OPTIONS="-XX:InitialTenuringThreshold=15 \
                        -XX:MaxTenuringThreshold=15 \
                        -XX:SurvivorRatio=2 \
                        -XX:NewRatio=2"

DEF_JAVA_DEBUGING_OPTIONS="-XX:+PrintGC \
                        -XX:+PrintGCDetails \
                        -XX:+PrintTenuringDistribution \
                        -XX:+PrintGCDateStamps \
                        -XX:+HeapDumpOnOutOfMemoryError"

