#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [[ "${FORCE:-0}" != 1 ]]; then
    # Check if artifactory plugin is installed
    debug "upgrade/bamboo: 52Checking artifactory plugin presence."
    RESULT_ARTIFACTORY_PLUGIN_EXISTS=$( run_cmd "ls ${INSTALL_DIR}/atlassian-bamboo/WEB-INF/lib/bamboo-artifactory-plugin-*.jar" )
    if [[ $( get_std_return ${RESULT_ARTIFACTORY_PLUGIN_EXISTS} ) == "0" ]]; then
        fatal "Artifactory Plugin detected at ${INSTALL_DIR}/atlassian-bamboo/WEB-INF/lib/bamboo-artifactory-plugin-*.jar. You will need to upgrade this manually or functionality will be lost. You can override this warning with --force"
        exit 32
    fi
fi

