#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Atlassian specific versioning of files, in case VERSION variable is not provided.
# Determine required version. if VERSION can not be found try to get it from TARBALL filename
parse_and_test_version ".zip"
# compare required version with current one, it has to be larger except the case that ALLOW_DOWNGRADE is set
if [[ "${ALLOW_DOWNGRADE:-0}" != 1 ]]; then
    OLD_VERSION=$( head -1 "${INSTANCE_DIR}/.version" )
    check_versions "${OLD_VERSION}" "${VERSION}"
fi

