#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

JVM_MINIMUM_MEMORY="${JVM_MINIMUM_MEMORY:-256m}"
JVM_MAXIMUM_MEMORY="${JVM_MAXIMUM_MEMORY:-512m}"
JVM_MAX_PERM_SIZE="${JVM_MAX_PERM_SIZE:-256m}"

CROWD_PROPERTIES_FILE="${CROWD_PROPERTIES_FILE:-${HOME_DIR}/crowd.properties}"
JAVA_APP_SPECIFIC_OPTIONS="${JAVA_APP_SPECIFIC_OPTIONS:--Dcrowd.properties=${CROWD_PROPERTIES_FILE}}"

log_set_variable JVM_MAXIMUM_MEMORY
log_set_variable JVM_MINIMUM_MEMORY
log_set_variable JVM_MAX_PERM_SIZE
log_set_variable CROWD_PROPERTIES_FILE
log_set_variable JAVA_APP_SPECIFIC_OPTIONS
