#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SYNCHRONY_START_SCRIPT="${INSTANCE_DIR}/install/start-synchrony.sh"
SYNCHRONY_OPTIONAL_OVERRIDES="${SYNCHRONY_OPTIONAL_OVERRIDES:-}"

# if a SYNCHRONY_OPTIONAL_OVERRIDES value is set then proceed
if [ -z "${SYNCHRONY_OPTIONAL_OVERRIDES}" ]; then
    debug "synchrony/modify.d/53jvm_params: SYNCHRONY_OPTIONAL_OVERRIDES has no value, OPTIONAL_OVERRIDES will be set to empty"
else
    debug "synchrony/modify.d/53jvm_params: attempting to set OPTIONAL_OVERRIDES values"
fi

augtool -LA ${AUGTOOL_DEBUG} <<EOF
set /augeas/load/properties/lens "Properties.lns"
set /augeas/load/properties/incl "${SYNCHRONY_START_SCRIPT}"
load
defvar prop /files${SYNCHRONY_START_SCRIPT}
set  \$prop/OPTIONAL_OVERRIDES "\"${SYNCHRONY_OPTIONAL_OVERRIDES}\""
save
print /augeas//error
EOF
