#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Check if application is installed
if [[ -f "${INSTANCE_DIR}/.state" ]]; then 
    STATE=$( head -1 "${INSTANCE_DIR}/.state" )
    if [[ "${STATE}" == "installed" || "${STATE}" == "modified" || "${STATE}" == "upgrading" ]]; then
        # Check that tarball is passed as param
        TARBALL="$PARAMS"
        if [[ -z "${TARBALL}" || ! -f "${TARBALL}" ]]; then
            fatal "install/expand_tarball: tarball \"${TARBALL}\" does not exist"
            exit 20
        fi
    else
        fatal "Can not make upgrade of application if state is not installed or modified."
        exit 34;
    fi
else
    fatal "Can not find .state file. Are you sure the application is installed."
    exit 33;
fi

