#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ -L /sbin/init ] &&  [[ $(readlink /sbin/init) == *"systemd"* ]]; then
    SERVICE_STATUS_SEARCH_STRING="Active: inactive"
else
    SERVICE_STATUS_SEARCH_STRING="stop"
fi

RESULT_SERVICE_STOPPED=$(run_cmd "service '${INSTANCE_NAME}' status | grep '${SERVICE_STATUS_SEARCH_STRING}'")
debug "${RESULT_SERVICE_STOPPED}"
if [[ "$(get_std_return ${RESULT_SERVICE_STOPPED})" == "0" ]]; then
    if [[ "${START_AFTER_UPGRADE:-0}" == "0"  ]]; then
        run_cmd start_service
    fi
fi

