#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BAMBOO_SERVER="${PARAMS}"

if [[ -z "$BAMBOO_SERVER" || ! "$BAMBOO_SERVER" =~ ^(ht|f)tps?:// ]]; then
	fatal "install/download_jar: invalid Bamboo server specified: \"${BAMBOO_SERVER}\""
    exit 20
fi

WGET_CMD=$( run_cmd wget -q -O "${INSTALL_DIR}/bamboo-agent-installer.jar" "${BAMBOO_SERVER}/agentServer/agentInstaller" )
debug "wget returned: ${WGET_CMD}"
if [[ "$(get_std_return ${WGET_CMD})" != "0" ]]; then
	fatal "install/download_jar: invalid Bamboo server specified: \"${BAMBOO_SERVER}\" - could not retrieve installation JAR"
    exit 20
fi
chown "${INSTANCE_USER}":"${INSTANCE_GROUP}" "${INSTALL_DIR}/bamboo-agent-installer.jar"

