#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

debug "install/extract_jar: Extracting '${INSTALL_DIR}/bamboo-agent-installer.jar'"
if [[ "${VERSION:-}" == "" ]]; then
    debug "VERSION not specified, defaulting to installing the agent without AGENT_SECURITY_TOKEN"
    EXTRACT_JAR_RESULT=$( run_cmd su - "${INSTANCE_USER}" -c \"java -Dbamboo.home=\\\"${HOME_DIR}\\\" -Ddisable_agent_auto_capability_detection=true -jar \\\"${INSTALL_DIR}/bamboo-agent-installer.jar\\\" \\\"${BAMBOO_SERVER}/agentServer\\\" install\" )
else
    VERSIONS_COMPARED_RESULT=$( run_cmd "version_comparison '5.10.0' '<' '${VERSION}'" )
    if [[ "$(get_std_return ${VERSIONS_COMPARED_RESULT})" == "0" ]]; then
        debug "Version greater than 5.10.0, optional AGENT_SECURITY_TOKEN"
        if [[ "${AGENT_SECURITY_TOKEN:-}" == "" ]]; then
            SECURITY_TOKEN_PARAM=""
        else
            SECURITY_TOKEN_PARAM="-t ${AGENT_SECURITY_TOKEN}"
        fi
        EXTRACT_JAR_RESULT=$( run_cmd su - "${INSTANCE_USER}" -c \"java -Dbamboo.home=\\\"${HOME_DIR}\\\" -Ddisable_agent_auto_capability_detection=true -jar \\\"${INSTALL_DIR}/bamboo-agent-installer.jar\\\" \\\"${BAMBOO_SERVER}/agentServer\\\" ${SECURITY_TOKEN_PARAM} install\" )
    else
        EXTRACT_JAR_RESULT=$( run_cmd su - "${INSTANCE_USER}" -c \"java -Dbamboo.home=\\\"${HOME_DIR}\\\" -Ddisable_agent_auto_capability_detection=true -jar \\\"${INSTALL_DIR}/bamboo-agent-installer.jar\\\" \\\"${BAMBOO_SERVER}/agentServer\\\" install\" )
    fi
fi
debug "${EXTRACT_JAR_RESULT}"
if [[ "$(get_std_return ${EXTRACT_JAR_RESULT})" != "0" ]]; then
    fatal "install/extract_jar: Error while extracting JAR: $(get_std_out ${EXTRACT_JAR_RESULT})"
    return 32
fi

