#!/bin/bash
# Copyright 2020 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# if the CLEAN_HOME_TEMP flag is set to 1 (true) then clean the directories (as long as they exist)
if [[  "${CLEAN_HOME_TEMP:-0}" -eq 1 ]]; then
        debug "jira/start/clean_temp: Attempting to clean Home Temp directory"

    # attempt to remove contents of temp from home
    REMOVE_DIR="${HOME_DIR}/tmp"
    if [[ -d "${REMOVE_DIR}" ]]; then
        debug "jira/start/clean_temp_work: Clearing content of ${REMOVE_DIR}"
        find "${REMOVE_DIR}" -mindepth 1 -maxdepth 1 -print0 | \
        sudo -u "${INSTANCE_USER}" bash -c "xargs -0rP 10 rm -rf"
    fi
fi