#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [[ ! -d "${INSTANCE_DIR}/avst-app/rc" ]]; then
    warn "common/regeneraterc/remove_rc_dir: Rc folder ${INSTANCE_DIR}/avst-app/rc does not exists, creating new one. If avstapp was not installed install it first or run prepare, this command should be used in case new avst-app version is installed to regenerate rc directory"
else
    debug "common/regeneraterc/remove_rc_dir: Removing folder ${INSTANCE_DIR}/avst-app/rc"
    rm -rf "${INSTANCE_DIR}/avst-app/rc"
fi