#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#Tomcat specifics
SHUTDOWN_PORT="${SHUTDOWN_PORT:-'8098'}" # TODO: Does this make sense to default?
CONTEXT_PATH="${CONTEXT_PATH:-}"
CONNECTOR_COUNT="${CONNECTOR_COUNT:-'1'}"
HTTP_PORT="${HTTP_PORT:-'8095'}" # TODO: Does this make sense to default?
DEFAULT_PORT="${HTTP_PORT}"
SCHEME="${SCHEME:-'http'}"
PROXY_NAME="${PROXY_NAME:-''}"
PROXY_PORT="${PROXY_PORT:-''}"

log_set_variable SHUTDOWN_PORT
log_set_variable CONTEXT_PATH
log_set_variable CONNECTOR_COUNT
log_set_variable HTTP_PORT
log_set_variable DEFAULT_PORT
log_set_variable SCHEME
