#!/bin/bash
# Copyright 2015 Adaptavist.com Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
if [[ ! -z "${DB_SETUP_DB:-}" ]]; then
  JIRA_XML_FILE="${HOME_DIR}/dbconfig.xml"

  # if dbconfig file does notexist create default, without this minimum augeas will not work
  if [[ ! -r "${JIRA_XML_FILE}" ]]; then
      echo "Could not find dbconfig.xml creating default"
  cat <<DB_FILE > "${JIRA_XML_FILE}"
<?xml version="1.0" encoding="UTF-8"?>
<jira-database-config>
  <jdbc-datasource>
  </jdbc-datasource>
</jira-database-config>
DB_FILE
  chown "${INSTANCE_USER}":"${INSTANCE_GROUP}" "${JIRA_XML_FILE}"
  fi

  if [ -z "${DB_TYPE:-}" -o \
       -z "${DB_JDBC_URL:-}" -o \
       -z "${DB_DRIVER:-}" -o \
       -z "${DB_USERNAME:-}" -o \
       -z "${DB_PASSWORD:-}" ]; then
    cat <<EOF
One of the mandatory variables to set the DB up is missing, these are:
DB_TYPE
DB_JDBC_URL
DB_DRIVER
DB_USERNAME
DB_PASSWORD
Note: you can also specify additional setup, if not following default values will be set:
  DB_DATASOURCE_NAME = defaultDS
  DB_DELEGATOR_NAME = default
  DB_MIN_POOL_SIZE = 20
  DB_MAX_POOL_SIZE = 20
  DB_POOL_MAX_WAIT = 30000
  DB_POOL_MAX_IDLE = 20
  DB_POOL_REMOVE_ABANDONED = true
  DB_POOL_REMOVE_ABANDONED_TIMEOUT = 300
  DB_POOL_TEST_ON_BORROW = false
  DB_VALIDATION_QUERY = select 1
  DB_MIN_EVIDENCE_IDLE_TIME_MILLIS = 60000
  DB_TIME_BETWEEN_EVICTION_RUNS_MILLIS = 300000
  DB_POOL_TEST_WHILE_IDLE = true
  DB_VALIDATION_QUERY_TIMEOUT = 3
EOF
    exit 12
  fi

  # if the DB is mysql add validation-query-timeout, if not do not
  if [[ "${DB_TYPE}" == mysql* ]]; then
    debug "jira/modify/setup_db: MySQL detected, setting validation-query-timeout"
    VAL_QUERY_TIMEOUT_SET="set \$datasources/validation-query-timeout/#text \"${DB_VALIDATION_QUERY_TIMEOUT:-3}\"" 
  else
    debug "jira/modify/setup_db: Non MySQL detected, skipping validation-query-timeout"
    VAL_QUERY_TIMEOUT_SET=""
  fi

  # if this is postgres and a DB Schema Name is provided, set it
  if [[ -n ${DB_SCHEMA_NAME:-} &&  "${DB_TYPE}" == postgres* ]]; then
      debug "jira/modify/setup_db: PostgreSQL database type and a DB Schema Name value detected, setting schema-name attribute to ${DB_SCHEMA_NAME}"
      DB_SCHEMA_NAME_SET="set \$database_config/schema-name/#text \"${DB_SCHEMA_NAME}\""
  else
      debug "jira/modify/setup_db: Not setting schema-name attribute"
      DB_SCHEMA_NAME_SET=""
  fi

  # TODO: Create variables from default values and adjust Note above and augtool code
  augtool -LA -e <<EOF
set /augeas/load/xml/lens "Xml.lns"
set /augeas/load/xml/incl "${JIRA_XML_FILE}"
load
defvar dbconfig_xml "/files/${JIRA_XML_FILE}"
defvar database_config \$dbconfig_xml/jira-database-config
defvar datasources \$database_config/jdbc-datasource
set \$database_config/name/#text "${DB_DATASOURCE_NAME:-defaultDS}"
set \$database_config/delegator-name/#text "${DB_DELEGATOR_NAME:-default}"
set \$database_config/database-type/#text "${DB_TYPE}"
${DB_SCHEMA_NAME_SET}
set \$datasources/url/#text "${DB_JDBC_URL}"
set \$datasources/driver-class/#text "${DB_DRIVER}"
set \$datasources/username/#text "${DB_USERNAME}"
set \$datasources/password/#text "${DB_PASSWORD}"
set \$datasources/pool-min-size/#text "${DB_MIN_POOL_SIZE:-20}"
set \$datasources/pool-max-size/#text "${DB_MAX_POOL_SIZE:-20}"
set \$datasources/pool-max-wait/#text "${DB_POOL_MAX_WAIT:-30000}"
set \$datasources/pool-max-idle/#text "${DB_POOL_MAX_IDLE:-20}"
set \$datasources/pool-remove-abandoned/#text "${DB_POOL_REMOVE_ABANDONED:-true}"
set \$datasources/pool-remove-abandoned-timeout/#text "${DB_POOL_REMOVE_ABANDONED_TIMEOUT:-300}"
set \$datasources/pool-test-on-borrow/#text "${DB_POOL_TEST_ON_BORROW:-false}"
set \$datasources/validation-query/#text "${DB_VALIDATION_QUERY:-select 1}"
set \$datasources/min-evictable-idle-time-millis/#text "${DB_MIN_EVIDENCE_IDLE_TIME_MILLIS:-60000}"
set \$datasources/time-between-eviction-runs-millis/#text "${DB_TIME_BETWEEN_EVICTION_RUNS_MILLIS:-300000}"
set \$datasources/pool-test-while-idle/#text "${DB_POOL_TEST_WHILE_IDLE:-true}"
${VAL_QUERY_TIMEOUT_SET}
save
print /augeas//error
EOF

fi
